#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: ..
    dockerfile: docker/dockerfile.cpu
  image: hrcnthu/visualnav:cpu-torch

  volumes:
    # GUI support for ROS applications
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix
    
    # Workspace volume
    - ../workspace:/workspace

  environment:
    - ROS_DOMAIN_ID=25
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/tmp/.docker.xauth

  # ROS2 communication settings
  network_mode: "host"
  ipc: host
  
  # Container settings
  tty: true
  stdin_open: true
  privileged: true
  stop_grace_period: 1s
  working_dir: /workspace


##############################
###   Container Services   ###
##############################
services:
  dev:
    <<: *common
    container_name: visualnav-dev-cpu
    command: ["/bin/bash"]
