#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: ..
    dockerfile: docker/dockerfile.cpu
  image: hrcnthu/visualnav:cpu-torch

  volumes:
    - $HOME/.Xauthority:/root/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ../workspace:/workspace

  environment:
    - DISPLAY=${DISPLAY}
    - XAUTHORITY=/root/.Xauthority
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}

  # ROS2 communication settings
  network_mode: "host"
  ipc: host
  
  # Container settings
  tty: true
  stdin_open: true
  privileged: true
  stop_grace_period: 1s
  working_dir: /workspace
  # user: "1000:1000"  # 預設 root 權限，若需非 root 請取消註解


##############################
###   Container Services   ###
##############################
services:
  dev:
    <<: *common
    container_name: visualnav-dev-cpu
    command: ["/bin/bash"]
