vint: 
  config_path: "../../train/config/vint.yaml"
  ckpt_path: "../../model/vint.pth"

late_fusion: 
  config_path: "../../train/config/late_fusion.yaml"
  ckpt_path: "../../model/vint.pth"

gnm: 
  config_path: "../../train/config/gnm.yaml"
  ckpt_path: "../../model/gnm.pth"

nomad: 
  config_path: "../../train/config/nomad.yaml"
  ckpt_path: "../../model/nomad.pth"
